v1.0.0 | Fixing actions

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -72,7 +72,7 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v5
         with:
-          python-version: '3.8'
+          python-version: '3.10.11'
 
       - name: Create venv
         run: python -m venv .venv
@@ -89,17 +89,14 @@ jobs:
       - name: Extract VERSION from config.py
         id: get_version
         run: |
-          set VERSION=
-          for /f "tokens=2 delims== " %%a in ('findstr /R "^VERSION[ ]*=" src\config.py') do set "VERSION=%%a"
-          if not defined VERSION (
-            echo Failed to extract VERSION from src/config.py
-            exit /b 1
-          )
-          set "VERSION=%VERSION: =%"
-          set "VERSION=%VERSION:\"=%"
-          echo Extracted VERSION: %VERSION%
-          echo VERSION=%VERSION%>>%GITHUB_ENV%
-        shell: cmd
+          $VERSION = (Select-String -Path "src/config.py" -Pattern '^VERSION\s*=\s*"v[0-9]+\.[0-9]+\.[0-9]+"').Matches | ForEach-Object { $_.Value.Split('=')[1].Trim().Trim('"') }
+          if (-not $VERSION) {
+            Write-Error "Failed to extract VERSION from src/config.py or invalid format. Expected VERSION = \"v*.*.*\""
+            exit 1
+          }
+          Write-Host "Extracted VERSION: $VERSION"
+          Write-Output "VERSION=$VERSION" | Add-Content -Path $env:GITHUB_ENV
+        shell: powershell
 
       - name: Debug VERSION
         run: |
